-- 错题本/AI习题表
CREATE TABLE IF NOT EXISTS `wrong_question` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `userId` bigint NOT NULL COMMENT '用户ID',
  `questionType` varchar(32) NOT NULL COMMENT '题目类型(choice/short_answer)',
  `questionContent` text NOT NULL COMMENT '题目内容',
  `options` text DEFAULT NULL COMMENT '选择题选项，JSON数组',
  `correctAnswer` text NOT NULL COMMENT '正确答案',
  `userAnswer` text COMMENT '用户答案',
  `analysis` text COMMENT '解析',
  `sourceType` varchar(32) DEFAULT NULL COMMENT '来源类型(course/practice/exam)',
  `sourceId` bigint DEFAULT NULL COMMENT '来源ID',
  `courseId` bigint DEFAULT NULL COMMENT '关联课程ID',
  `chapterId` bigint DEFAULT NULL COMMENT '关联章节ID',
  `sectionId` bigint DEFAULT NULL COMMENT '关联小节ID',
  `difficulty` tinyint DEFAULT 1 COMMENT '难度：1-简单，2-中等，3-困难',
  `aiGenerated` tinyint DEFAULT 0 COMMENT '是否AI生成：0-否，1-是',
  `masteryLevel` tinyint NOT NULL DEFAULT 0 COMMENT '掌握程度(0-未掌握 1-部分掌握 2-已掌握)',
  `reviewCount` int NOT NULL DEFAULT 0 COMMENT '复习次数',
  `lastReviewTime` datetime DEFAULT NULL,
  `nextReviewTime` datetime DEFAULT NULL,
  `isDelete` tinyint NOT NULL DEFAULT 0,
  `createTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_userId_type` (`userId`, `questionType`),
  KEY `idx_course_chapter` (`courseId`, `chapterId`),
  KEY `idx_aiGenerated` (`aiGenerated`),
  KEY `idx_nextReviewTime` (`nextReviewTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='错题本/AI习题';
